hasTryCatch
===========

let foo = fn(arg)
  try
      fails_on_1(arg)
      fails_on_2(arg)
      fails_on_3(arg)
  catch let err
      return err
  return 99

*

Languages *with* hasTryCatch include bog

*

Languages *without* hasTryCatch include Jule, Speedie

*

View all concepts with or missing a *hasTryCatch* measurement
 https://pldb.io/../lists/explorer.html#columns=rank~id~appeared~tags~creators~hasTryCatch&searchBuilder=%7B%22criteria%22%3A%5B%7B%22condition%22%3A%22null%22%2C%22data%22%3A%22hasTryCatch%22%2C%22origData%22%3A%22hasTryCatch%22%2C%22type%22%3A%22num%22%2C%22value%22%3A%5B%5D%7D%5D%2C%22logic%22%3A%22AND%22%7D missing
 https://pldb.io/../lists/explorer.html#columns=rank~id~appeared~tags~creators~hasTryCatch&searchBuilder=%7B%22criteria%22%3A%5B%7B%22condition%22%3A%22!null%22%2C%22data%22%3A%22hasTryCatch%22%2C%22origData%22%3A%22hasTryCatch%22%2C%22type%22%3A%22num%22%2C%22value%22%3A%5B%5D%7D%5D%2C%22logic%22%3A%22AND%22%7D with

View source
